title: 人才招募
description: 加入我們的團隊，一同創造更好的未來
baseurl: "/recruit"
url: "https://raywang1025.github.io"

# 主題設定
theme: minima

# 導航選單
header_pages:
  - about.md
  - positions.md
  - contact.md

# 社交媒體連結
social_links:
  linkedin: company/raywang

# 多語言設定
languages:
  - zh-TW
  - en

# 構建設定
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed
  sourcemap: never
incremental: true
livereload: true

# 性能優化
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# 資源優化
assets:
  compression: true
  sources:
    - assets/js
    - assets/css
    - assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  cache: true
  cdn: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - wp-content
  - wp-admin
  - wp-includes
  - .git
  - .github
  - .gitignore
  - .sass-cache
  - .jekyll-cache
  - .DS_Store

# 快取設定
keep_files:
  - .git
  - .svn
  - assets
  - images
  - sw.js 